# Generated by Django 3.1.7 on 2021-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransactionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now_add=True, db_column='updated_on', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', null=True)),
                ('created_by', models.IntegerField(db_column='created_by', default=100, null=True)),
                ('updated_by', models.IntegerField(db_column='updated_by', default=100, null=True)),
                ('status', models.CharField(db_column='status', max_length=50, null=True)),
                ('customer_id', models.IntegerField(db_column='customer_id')),
                ('card_value', models.FloatField(db_column='card_value')),
                ('transaction_date', models.DateTimeField(db_column='transaction_date', null=True)),
            ],
            options={
                'db_table': 'card_transaction_info',
            },
        ),
    ]
