# Generated by Django 3.1.7 on 2021-02-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transactions', '0002_cardtransactionpredictevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardtransactionpredictevent',
            table='card_transaction_predict_event',
        ),
    ]
